name: workflow1
on: [push]
jobs:
  hey:
    runs-on: ubuntu-latest
    steps:
      - run: echo "AA"
      - uses: Ch1mple/my-workflow-nodejs@main
      - uses: Ch1mple/my-workflow-docker@main
        with:
          FIRST_NAME: 'John Tre'
      - name: Get the output time
        run: echo "The time was ${{ steps.hey.outputs.time }}"
